### ISSUE TITLE
Boucle inutile 

### ISSUE THREAD

**Issue by focardi-francois-philippe** [Felicien2B/univ#1]
https://github.com/Felicien2B/univ/blob/16a1efbcd6948b64e5e566f769f1e5b5754e6b6a/L3%20Info/atelier4/atelier4_ex2.py#L127
with open(nom_fichier, "r") as fichier:
        dictionnaire = fichier.read() #lit la totalite du fichier ensuite possibilite d'utiliser des fonction directement exemple fichier.read().split('\n') supprimera tout les \n

**Comment by Felicien2B** [comment]
https://github.com/Felicien2B/univ/blob/3dc3f0218f2b21837b6f5bd29d47d0d9953f14ca/L3%20Info/atelier4/atelier4_ex2.py#L125
