### ISSUE TITLE
reprendre le docstring

### ISSUE THREAD

**Issue by AlexandreDML** [Felicien2B/univ#2]
https://github.com/Felicien2B/univ/blob/f01e9b3b2e7db15b816cc49d4a06b6c58d03f46e/L3%20Info/atelier3/atelier3.py#L573

**Comment by Felicien2B** [comment]
https://github.com/Felicien2B/univ/blob/fb5ec61872f8fb7830c6c77aad75b76ad076be86/L3%20Info/atelier3/atelier3.py#L581
